spring:
  datasource:
    url: jdbc:postgresql://db.qcphkexqxumrlpdrlgiv.supabase.co:5432/postgres
    password: EE-nFeG!-e-v(@9
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    hidden method:
      filter:
        enabled: true